"""
DEPRECATED — DO NOT USE. This file is a dead copy of dbma.py.

Active entry point: dbma.py (Sprint 1 data layer only)
This file will be archived when Sprint 2 features are enabled.

To run DBMA:
    streamlit run dbma.py

DO NOT edit this file — changes here will NOT propagate to the active app.
"""

from __future__ import annotations

import json
import logging
import time
from pathlib import Path
from typing import Any, Dict, List, Optional

import chromadb
import ollama
import pandas as pd
import streamlit as st
if not logging.getLogger().handlers:
    logging.basicConfig(level=logging.INFO)


def safe_log_exception(msg: str):
    try:
        logging.getLogger(__name__).error(msg, exc_info=False)
    except Exception:
        pass


APP_VERSION = "0.6.4"
PROJECT_ROOT = Path(__file__).resolve().parent
RAW_DIR = PROJECT_ROOT / "data" / "RAW"
OUTPUT_DIR = PROJECT_ROOT / "data" / "제련완성본"
DOCS_DIR = PROJECT_ROOT / "docs"
LOGS_DIR = PROJECT_ROOT / "logs"
TODO_MD = DOCS_DIR / "dbmar_todo_progress_board.md"
PROGRESS_CSV = DOCS_DIR / "dbmar_progress_snapshot.csv"
EVENTS_JSONL = LOGS_DIR / "project_events.jsonl"
BENCH_CSV = DOCS_DIR / "rag_benchmark.csv"
CHROMA_DIR = PROJECT_ROOT / "chroma_db"
COLLECTION_NAME = "dbmar_docs"

EMBED_MODEL_OPTIONS = ["bge-m3", "nomic-embed-text", "mxbai-embed-large"]
GEN_MODEL_OPTIONS = ["llama3.1", "gemma3:4b", "llama3:8b"]
DEFAULT_EMBED_MODEL = "bge-m3:latest"
DEFAULT_GEN_MODEL = "llama3.1"

SUPPORTED_EXTS = {".pdf", ".txt", ".md", ".docx", ".epub", ".html", ".htm", ".rtf"}
DEFAULT_CHUNK_SIZE = 1200
DEFAULT_CHUNK_OVERLAP = 120
RAG_MIN_LEN = 80
RAG_MAX_NOISE = 70.0
RAG_TOP_K = 4
DEFAULT_TEMPERATURE = 0.2

DEFAULT_PROGRESS = [
    {"영역": "멀티 포맷 추출", "진행률": 75, "상태": "DOING"},
    {"영역": "텍스트 정제", "진행률": 60, "상태": "DOING"},
    {"영역": "청킹 전략", "진행률": 45, "상태": "DOING"},
    {"영역": "임베딩/인덱싱", "진행률": 50, "상태": "DOING"},
    {"영역": "평가 루프", "진행률": 35, "상태": "DOING"},
    {"영역": "로그/추적성", "진행률": 30, "상태": "TODO"},
    {"영역": "UI/탭 구조", "진행률": 25, "상태": "TODO"},
    {"영역": "문서화/운영", "진행률": 65, "상태": "DOING"},
]

EVENT_TO_AREA = {
    "parse_completed": "멀티 포맷 추출",
    "clean_completed": "텍스트 정제",
    "chunk_completed": "청킹 전략",
    "index_completed": "임베딩/인덱싱",
    "eval_completed": "평가 루프",
    "log_completed": "로그/추적성",
    "ui_completed": "UI/탭 구조",
    "docs_completed": "문서화/운영",
}


def ensure_dirs():
    RAW_DIR.mkdir(parents=True, exist_ok=True)
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    DOCS_DIR.mkdir(parents=True, exist_ok=True)
    LOGS_DIR.mkdir(parents=True, exist_ok=True)
    CHROMA_DIR.mkdir(parents=True, exist_ok=True)


def normalize_text(text: str) -> str:
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    lines = [ln.rstrip() for ln in text.split("\n")]
    text = "\n".join(lines)
    text = "\n".join(line for line in text.split("\n") if line.strip())
    return text.strip()


def safe_stem(name: str) -> str:
    stem = Path(name).stem
    for ch in [" ", "/", "\\", ":", "*", "?", '"', "<", ">", "|"]:
        stem = stem.replace(ch, "_")
    return stem


def detect_language_hint(text: str) -> str:
    if not text:
        return "unknown"
    hangul = sum(1 for ch in text if "\uac00" <= ch <= "\ud7a3")
    latin = sum(1 for ch in text if ch.isascii() and ch.isalpha())
    if hangul > latin:
        return "ko"
    if latin > hangul:
        return "en"
    return "mixed"


def estimate_noise_score(text: str) -> dict:
    if not text:
        return {"score": 100.0, "level": "EMPTY", "usable": False, "reason": "empty text", "metrics": {}}

    chars = len(text)
    lines = [ln for ln in text.split("\n") if ln.strip()]
    line_count = max(1, len(lines))
    letters = sum(1 for ch in text if ch.isalpha())
    digits = sum(1 for ch in text if ch.isdigit())
    control = sum(1 for ch in text if ord(ch) < 32 and ch not in "\n\t")
    replacement = text.count("")

    short_lines = sum(1 for ln in lines if len(ln.strip()) < 20)
    short_line_ratio = short_lines / line_count

    repeat_runs = 0
    prev = ""
    run = 0
    for ch in text:
        if ch == prev:
            run += 1
        else:
            run = 1
            prev = ch
        if run >= 5:
            repeat_runs += 1

    alpha_ratio = letters / chars
    digit_ratio = digits / chars
    ctrl_ratio = control / chars
    repl_ratio = replacement / chars

    score = 0.0
    score += max(0, (1 - alpha_ratio)) * 12
    score += min(1, digit_ratio * 3) * 6
    score += min(1, ctrl_ratio * 25) * 35
    score += min(1, repl_ratio * 40) * 40
    score += min(1, short_line_ratio) * 10
    score += min(1, repeat_runs / 20) * 8
    score = max(0.0, min(100.0, score))

    if score >= 70:
        level, usable = "HIGH", False
    elif score >= 40:
        level, usable = "MEDIUM", True
    elif score >= 15:
        level, usable = "LOW", True
    else:
        level, usable = "GOOD", True

    reason = "ok"
    if replacement > 0:
        reason = "replacement chars detected"
    elif control > 0:
        reason = "control chars detected"
    elif short_line_ratio > 0.5:
        reason = "many short lines"
    elif repeat_runs > 0:
        reason = "repeated patterns detected"

    return {
        "score": round(score, 1),
        "level": level,
        "usable": usable,
        "reason": reason,
        "metrics": {
            "chars": chars,
            "alpha_ratio": round(alpha_ratio, 3),
            "digit_ratio": round(digit_ratio, 3),
            "ctrl_ratio": round(ctrl_ratio, 3),
            "repl_ratio": round(repl_ratio, 3),
            "short_line_ratio": round(short_line_ratio, 3),
            "repeat_runs": repeat_runs,
        },
    }

def score_to_color(score: float) -> str:
    if score >= 70:
        return "#e74c3c"
    if score >= 40:
        return "#f39c12"
    if score >= 15:
        return "#f1c40f"
    return "#2ecc71"


def score_to_label(score: float) -> str:
    if score >= 70:
        return "HIGH NOISE"
    if score >= 40:
        return "MEDIUM NOISE"
    if score >= 15:
        return "LOW NOISE"
    return "GOOD"


def append_event(event, status="DONE", delta=5, note="", run_id="manual"):
    ensure_dirs()
    entry = {"event": event, "status": status, "delta": delta, "note": note, "run_id": run_id, "ts": pd.Timestamp.now().isoformat(timespec="seconds")}
    try:
        with EVENTS_JSONL.open("a", encoding="utf-8") as f:
            f.write(json.dumps(entry, ensure_ascii=False) + "\n")
    except Exception as e:
        safe_log_exception(f"event write failed: {e}")
    try:
        df = load_progress_df()
        area = EVENT_TO_AREA.get(event)
        if area and area in set(df["영역"]):
            i = df.index[df["영역"] == area][0]
            current = int(df.at[i, "진행률"])
            if status == "DONE":
                current = min(100, current + delta)
                df.at[i, "상태"] = "DONE" if current >= 100 else "DOING"
            else:
                df.at[i, "상태"] = status
            df.at[i, "진행률"] = current
            save_progress_df(df)
            refresh_todo_doc(df)
        return df
    except Exception as e:
        safe_log_exception(f"append_event failed: {e}")
        return load_progress_df()


def load_progress_df():
    ensure_dirs()
    if PROGRESS_CSV.exists():
        try:
            return pd.read_csv(PROGRESS_CSV)
        except Exception:
            pass
    df = pd.DataFrame(DEFAULT_PROGRESS)
    df.to_csv(PROGRESS_CSV, index=False)
    return df


def save_progress_df(df):
    ensure_dirs()
    df.to_csv(PROGRESS_CSV, index=False)


def refresh_todo_doc(df=None):
    try:
        ensure_dirs()
        if df is None:
            df = load_progress_df()
        avg = float(df["진행률"].mean()) if not df.empty else 0.0
        todo = int((df["상태"] == "TODO").sum())
        blocked = int((df["상태"] == "BLOCKED").sum())
        auto = ["", "---", "## Auto Summary", f"- 전체 평균 진행률: {avg:.1f}%", f"- TODO 수: {todo}", f"- BLOCKED 수: {blocked}", "", "### 영역별 상태"]
        for _, row in df.iterrows():
            auto.append(f"- {row['영역']}: {int(row['진행률'])}% / {row['상태']}")
        if TODO_MD.exists():
            base = TODO_MD.read_text(encoding="utf-8").split("\n---\n## Auto Summary")[0].rstrip()
        else:
            base = "# DBMAr Project State\n\n이 파일은 프로젝트 모니터링의 기준 문서입니다."
        TODO_MD.write_text(base + "\n" + "\n".join(auto) + "\n", encoding="utf-8")
    except Exception as e:
        safe_log_exception(f"refresh_todo_doc failed: {e}")


def cleanup_cache():
    for fn in ("clear", "cache_data"):
        obj = getattr(st, fn, None)
        if callable(obj):
            try:
                obj.clear()
            except Exception as e:
                safe_log_exception(f"cleanup_cache {fn} failed: {e}")





def extract_pdf(path: Path, use_ocr: bool = False) -> str:
    opts = PdfPipelineOptions()
    opts.do_ocr = use_ocr
    if use_ocr:
        opts.ocr_options = EasyOcrOptions()
    converter = DocumentConverter(format_options={InputFormat.PDF: PdfFormatOption(pipeline_options=opts)})
    result = converter.convert(str(path))
    doc = getattr(result, "document", None)
    if doc is None:
        return ""
    text = getattr(doc, "export_to_markdown", None)
    if callable(text):
        return text()
    text = getattr(doc, "text", "")
    return text or ""


def extract_txt(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="ignore")


def extract_md(path: Path) -> str:
    return path.read_text(encoding="utf-8", errors="ignore")


def extract_docx(path: Path) -> str:
    doc = Document(str(path))
    return "\n".join(p.text for p in doc.paragraphs)


def extract_html(path: Path) -> str:
    html = path.read_text(encoding="utf-8", errors="ignore")
    soup = BeautifulSoup(html, "html.parser")
    return soup.get_text("\n")


def extract_rtf(path: Path) -> str:
    data = path.read_text(encoding="utf-8", errors="ignore")
    return rtf_to_text(data)


def extract_epub(path: Path) -> str:
    book = epub.read_epub(str(path))
    chunks = []
    for item in book.get_items():
        if item.get_type() == ITEM_DOCUMENT:
            try:
                soup = BeautifulSoup(item.get_content(), "html.parser")
                chunks.append(soup.get_text("\n"))
            except Exception:
                pass
    return "\n".join(chunks)


def extract_text(path: Path, use_ocr: bool = False) -> str:
    ext = path.suffix.lower()
    if ext == ".pdf":
        return extract_pdf(path, use_ocr=use_ocr)
    if ext == ".txt":
        return extract_txt(path)
    if ext == ".md":
        return extract_md(path)
    if ext == ".docx":
        return extract_docx(path)
    if ext == ".epub":
        return extract_epub(path)
    if ext in {".html", ".htm"}:
        return extract_html(path)
    if ext == ".rtf":
        return extract_rtf(path)
    return ""


def clean_text(text: str) -> str:
    text = normalize_text(text)
    text = text.replace("\xa0", " ")
    text = "\n".join(line.strip() for line in text.split("\n"))
    text = "\n".join(line for line in text.split("\n") if line.strip())
    return text.strip()


def chunk_text(text: str, chunk_size: int = None, chunk_overlap: int = None,
               doc_type: str = "default") -> tuple[list[str], dict]:
    """
    옵티마이저 우선 실행.
    chunk_size/chunk_overlap 이 명시적으로 전달되면 단회성 청킹(기존 호환).
    반환: (chunks, params)
    """
    from core.chunking_optimizer import chunk_once, optimize_chunks
    if chunk_size and chunk_overlap:
        result = chunk_once(text, chunk_size, chunk_overlap)
    else:
        result = optimize_chunks(text, doc_type)
    return result.chunks, result.params


def write_outputs(src: Path, text: str, chunks: list[str]):
    ensure_dirs()
    stem = safe_stem(src.name)
    md_path = OUTPUT_DIR / f"{stem}.md"
    chunk_path = OUTPUT_DIR / f"{stem}_chunks.txt"
    md_path.write_text(text, encoding="utf-8")
    chunk_path.write_text("\n\n".join(f"[CHUNK {i+1}]\n{c}" for i, c in enumerate(chunks)), encoding="utf-8")
    return md_path, chunk_path


def move_source(src: Path):
    target = OUTPUT_DIR / src.name
    try:
        if src.resolve() == target.resolve():
            return target
        if target.exists():
            target = OUTPUT_DIR / f'{safe_stem(src.name)}_{pd.Timestamp.now().strftime("%Y%m%d%H%M%S")}{src.suffix}'
        src.rename(target)
        return target
    except Exception as e:
        safe_log_exception(f"move_source failed: {e}")
        return src


def scan_raw_files():
    ensure_dirs()
    files = []
    for p in RAW_DIR.iterdir():
        if p.is_file() and p.suffix.lower() in SUPPORTED_EXTS:
            files.append(p)
    return sorted(files, key=lambda x: x.name.lower())


def get_vector_client():
    return chromadb.PersistentClient(path=str(CHROMA_DIR))


def get_collection():
    client = get_vector_client()
    return client.get_or_create_collection(name=COLLECTION_NAME)


def rag_chunk_text(text: str, chunk_size: int = DEFAULT_CHUNK_SIZE, overlap: int = DEFAULT_CHUNK_OVERLAP) -> List[str]:
    splitter = RecursiveCharacterTextSplitter(chunk_size=chunk_size, chunk_overlap=overlap, separators=["\n\n", "\n", ". ", " ", ""])
    return splitter.split_text(text or "")


def read_indexable_docs(selected_files: Optional[List[str]] = None, input_dir: str = str(OUTPUT_DIR)) -> List[Dict[str, Any]]:
    base = Path(input_dir)
    docs = []
    if not base.exists():
        return docs
    allowed = set(selected_files or [])
    for p in sorted(base.glob("*.md")):
        if allowed and p.name not in allowed:
            continue
        try:
            docs.append({"source": p.name, "text": p.read_text(encoding="utf-8", errors="ignore")})
        except Exception:
            pass
    return docs


def list_ollama_models() -> List[str]:
    try:
        import requests
        r = requests.get("http://localhost:11434/api/tags", timeout=5)
        r.raise_for_status()
        data = r.json()
        return [m.get("name") for m in data.get("models", []) if m.get("name")]
    except Exception:
        return []


def _model_supports_embeddings(model: str) -> bool:
    name = (model or "").lower()
    keywords = ["embed", "bge", "nomic", "mxbai", "e5", "snowflake"]
    return any(k in name for k in keywords)


def _embed_texts(texts: List[str], model: str = DEFAULT_EMBED_MODEL) -> List[List[float]]:
    try:
        return ollama.embed(model=model, input=texts)["embeddings"]
    except Exception as e:
        if "tokenize" in str(e).lower() or len(texts) > 1:
            out = []
            for t in texts:
                if not t.strip():
                    continue
                try:
                    out.extend(ollama.embed(model=model, input=t)["embeddings"])
                except Exception:
                    continue
            if out:
                return out
        raise


def _rag_noise(text: str) -> float:
    return estimate_noise_score(text)["score"]


def build_rag_store(
    selected_files: Optional[List[str]] = None,
    input_dir: str = str(OUTPUT_DIR),
    embed_model: str = DEFAULT_EMBED_MODEL,
    chunk_size: int = DEFAULT_CHUNK_SIZE,
    overlap: int = DEFAULT_CHUNK_OVERLAP,
    min_len: int = RAG_MIN_LEN,
    max_noise: float = RAG_MAX_NOISE,
):
    ensure_dirs()
    collection = get_collection()
    docs = read_indexable_docs(selected_files=selected_files, input_dir=input_dir)
    ids, documents, metadatas = [], [], []
    for doc in docs:
        chunks = rag_chunk_text(doc["text"], chunk_size=chunk_size, overlap=overlap)
        for j, chunk in enumerate(chunks):
            if len(chunk.strip()) < min_len:
                continue
            noise = _rag_noise(chunk)
            if noise >= max_noise:
                continue
            ids.append(f"{doc['source']}::{j}")
            documents.append(chunk)
            metadatas.append({"source": doc["source"], "chunk": j, "noise": noise, "len": len(chunk)})
    if not ids:
        return {"documents": len(docs), "chunks": 0, "indexed": 0, "collection": COLLECTION_NAME, "chroma_dir": str(CHROMA_DIR)}
    embeddings = _embed_texts(documents, model=embed_model)
    collection.upsert(ids=ids, embeddings=embeddings, documents=documents, metadatas=metadatas)
    return {"documents": len(docs), "chunks": len(documents), "indexed": len(ids), "collection": COLLECTION_NAME, "chroma_dir": str(CHROMA_DIR), "embed_model": embed_model}


def query_rag(
    question: str,
    embed_model: str = DEFAULT_EMBED_MODEL,
    gen_model: str = DEFAULT_GEN_MODEL,
    top_k: int = RAG_TOP_K,
    temperature: float = DEFAULT_TEMPERATURE,
    max_noise: float = RAG_MAX_NOISE,
) -> Dict[str, Any]:
    ensure_dirs()
    collection = get_collection()
    embedding_enabled = _model_supports_embeddings(embed_model)
    q_emb = None
    embed_error = None

    if embedding_enabled:
        try:
            q_emb = ollama.embed(model=embed_model, input=question)["embeddings"][0]
        except Exception as e:
            embed_error = str(e)
            embedding_enabled = False

    results = {"documents": [[]], "metadatas": [[]], "ids": [[]]}
    if q_emb is not None:
        try:
            results = collection.query(query_embeddings=[q_emb], n_results=top_k)
        except Exception as e:
            embed_error = f"{embed_error}; {e}" if embed_error else str(e)
            embedding_enabled = False

    docs = results.get("documents", [[]])[0]
    metas = results.get("metadatas", [[]])[0]
    ids = results.get("ids", [[]])[0]
    sources = []
    filtered_docs = []
    for i, doc in enumerate(docs):
        meta = metas[i] if i < len(metas) else {}
        source = meta.get("source", "unknown") if isinstance(meta, dict) else "unknown"
        chunk = meta.get("chunk", i) if isinstance(meta, dict) else i
        noise = meta.get("noise", None) if isinstance(meta, dict) else None
        if noise is not None and noise >= max_noise:
            continue
        filtered_docs.append(doc)
        sources.append({"rank": len(filtered_docs), "id": ids[i] if i < len(ids) else "", "source": source, "chunk": chunk, "noise": noise, "snippet": doc[:240].replace("\n", " ")})
    if filtered_docs:
        context = "\n\n".join(filtered_docs)
        prompt = f"""아래 문맥만 사용해 답하라. 모르면 모른다고 말하라.

문맥:
{context}

질문:
{question}
"""
    else:
        prompt = f"""다음 질문에 답하라. 현재 임베딩 기반 검색을 사용할 수 없으므로, 일반 지식으로만 답하되 불확실하면 그렇게 밝혀라.

질문:
{question}
"""
    answer = ollama.generate(model=gen_model, prompt=prompt, options={"temperature": temperature})["response"]
    if embed_error and not filtered_docs:
        answer = answer + f"\n\n[주의] embedding 검색 비활성화: {embed_error}"
    return {"question": question, "answer": answer, "contexts": filtered_docs, "sources": sources, "embed_model": embed_model, "gen_model": gen_model, "embedding_enabled": embedding_enabled, "embed_error": embed_error, "temperature": temperature}


def append_benchmark_row(embed_model: str, gen_model: str, chunk_size: int, overlap: int, top_k: int, docs: int, chunks: int, q: str, answer: str, elapsed: float, source_count: int):
    ensure_dirs()
    row = pd.DataFrame([{
        "ts": pd.Timestamp.now().isoformat(timespec="seconds"),
        "embed_model": embed_model,
        "gen_model": gen_model,
        "chunk_size": chunk_size,
        "overlap": overlap,
        "top_k": top_k,
        "docs": docs,
        "chunks": chunks,
        "question": q,
        "answer_len": len(answer or ""),
        "elapsed_sec": round(elapsed, 3),
        "source_count": source_count,
    }])
    if BENCH_CSV.exists():
        base = pd.read_csv(BENCH_CSV)
        out = pd.concat([base, row], ignore_index=True)
    else:
        out = row
    out.to_csv(BENCH_CSV, index=False)


def render_noise_bar(noise: float, usable: bool, level: str):
    color = score_to_color(noise)
    width = max(0, min(100, 100 - int(noise)))
    label = score_to_label(noise)
    usable_text = "사용 가능" if usable else "주의"
    st.markdown(f"""
        <div style="border:1px solid #ddd;border-radius:8px;padding:12px;margin:8px 0;">
            <div style="display:flex;justify-content:space-between;align-items:center;margin-bottom:6px;">
                <strong>{label}</strong>
                <span>{usable_text} · noise {noise:.1f}/100</span>
            </div>
            <div style="background:#eee;border-radius:999px;height:14px;overflow:hidden;">
                <div style="width:{width}%;background:{color};height:14px;"></div>
            </div>
            <div style="margin-top:6px;font-size:0.92em;color:#666;">level: {level}</div>
        </div>
        """, unsafe_allow_html=True)


def init_chat_state():
    if "rag_chat" not in st.session_state:
        st.session_state["rag_chat"] = [{"role": "assistant", "content": "안녕하세요. 무엇을 찾고 있나요?"}]
    if "rag_input" not in st.session_state:
        st.session_state["rag_input"] = ""
    if "rag_mode" not in st.session_state:
        st.session_state["rag_mode"] = "hybrid"
    if "rag_show_context" not in st.session_state:
        st.session_state["rag_show_context"] = True


def chat_user_bubble(text: str):
    st.markdown(
        f"""
        <div style="display:flex;justify-content:flex-end;margin:10px 0;">
          <div style="max-width:78%;background:linear-gradient(135deg,#6d5efc,#8f7cff);color:white;padding:14px 16px;border-radius:18px 18px 4px 18px;box-shadow:0 8px 24px rgba(109,94,252,.18);">
            <div style="font-size:13px;opacity:.9;margin-bottom:6px;">You</div>
            <div style="white-space:pre-wrap;line-height:1.55;">{text}</div>
          </div>
        </div>
        """,
        unsafe_allow_html=True,
    )


def chat_assistant_bubble(text: str, source_count: int = 0, mode: str = "hybrid"):
    badge = "RAG" if mode == "hybrid" else "GEN"
    st.markdown(
        f"""
        <div style="display:flex;justify-content:flex-start;margin:10px 0;">
          <div style="max-width:82%;background:rgba(255,255,255,0.82);backdrop-filter:blur(10px);border:1px solid rgba(120,120,120,.18);padding:14px 16px;border-radius:18px 18px 18px 4px;box-shadow:0 8px 24px rgba(0,0,0,.06);">
            <div style="display:flex;justify-content:space-between;gap:12px;font-size:13px;opacity:.75;margin-bottom:6px;">
              <span>Assistant</span><span>{badge} · {source_count} sources</span>
            </div>
            <div style="white-space:pre-wrap;line-height:1.6;">{text}</div>
          </div>
        </div>
        """,
        unsafe_allow_html=True,
    )


def pick_docs_for_embedding():
    ensure_dirs()
    files = sorted([p for p in OUTPUT_DIR.glob("*.md") if p.is_file()], key=lambda x: x.name.lower())
    if not files:
        return []
    cols = st.columns(2)
    with cols[0]:
        st.markdown("### 임베딩할 자료 선택")
    with cols[1]:
        select_all = st.checkbox("전체 선택", value=True, key="embed_select_all")
    choices = [p.name for p in files]
    default = choices if select_all else choices[:min(5, len(choices))]
    selected = st.multiselect("대상 md 파일", choices, default=default, key="embed_doc_picker")
    return selected


def render_trendy_chat_tab(embed_model: str, gen_model: str, chunk_size: int, chunk_overlap: int, top_k: int, temperature: float):
    init_chat_state()
    st.subheader("RAG Chat")
    st.caption("모던한 채팅 UI + RAG fallback")

    top_left, top_right = st.columns([4, 1])
    with top_left:
        st.markdown(
            """
            <div style="padding:14px 16px;border:1px solid rgba(120,120,120,.14);border-radius:18px;background:linear-gradient(180deg,rgba(255,255,255,.9),rgba(248,249,255,.9));">
              <div style="font-size:15px;font-weight:600;margin-bottom:4px;">RAG Conversation</div>
              <div style="font-size:13px;opacity:.75;">질문을 입력하면 검색 결과를 자동으로 섞어 답변합니다.</div>
            </div>
            """,
            unsafe_allow_html=True,
        )
    with top_right:
        st.metric("Top K", top_k)

    sidebar1, sidebar2 = st.columns([1, 1])
    with sidebar1:
        st.session_state["rag_mode"] = st.selectbox("Mode", ["hybrid", "gen_only"], index=0 if st.session_state["rag_mode"] == "hybrid" else 1)
    with sidebar2:
        st.session_state["rag_show_context"] = st.toggle("Show context", value=st.session_state["rag_show_context"])

    st.markdown("### 임베딩 후보")
    selected_docs = pick_docs_for_embedding()
    if selected_docs:
        st.caption(f"선택된 문서: {len(selected_docs)}개")
        st.dataframe(pd.DataFrame({"file": selected_docs}), use_container_width=True, hide_index=True)

    c1, c2, c3 = st.columns(3)
    with c1:
        build_clicked = st.button("임베딩 인덱스 빌드", use_container_width=True)
    with c2:
        if st.button("벤치마크 기록 보기", use_container_width=True):
            if BENCH_CSV.exists():
                st.dataframe(pd.read_csv(BENCH_CSV), use_container_width=True, hide_index=True)
            else:
                st.info("벤치마크 기록이 없습니다.")
    with c3:
        st.caption(f"Collection: {COLLECTION_NAME}")
        st.caption(f"Embed: {embed_model}")
        st.caption(f"Gen: {gen_model}")
        if not _model_supports_embeddings(embed_model):
            st.warning("선택한 embedding model이 embeddings용으로 보이지 않습니다.")

    if build_clicked:
        if not selected_docs:
            st.warning("임베딩할 자료를 먼저 선택하세요.")
        else:
            out = build_rag_store(
                selected_files=selected_docs,
                input_dir=str(OUTPUT_DIR),
                embed_model=embed_model,
                chunk_size=chunk_size,
                overlap=chunk_overlap,
            )
            st.success(f"{out['documents']} docs, {out['chunks']} chunks indexed")

    for msg in st.session_state["rag_chat"]:
        if msg["role"] == "user":
            chat_user_bubble(msg["content"])
        else:
            chat_assistant_bubble(msg["content"], msg.get("source_count", 0), msg.get("mode", "hybrid"))

    st.markdown("<div style='height:8px'></div>", unsafe_allow_html=True)
    c1, c2, c3 = st.columns([8, 1, 1])
    with c1:
        prompt = st.text_input("", placeholder="질문을 입력하세요… 예: 이 문서에서 핵심 요점은?", label_visibility="collapsed", key="rag_input")
    with c2:
        ask = st.button("Send", use_container_width=True)
    with c3:
        clear = st.button("Clear", use_container_width=True)

    if clear:
        st.session_state["rag_chat"] = [{"role": "assistant", "content": "채팅을 초기화했습니다.", "source_count": 0, "mode": "gen_only"}]
        st.session_state["rag_input"] = ""
        st.rerun()

    if ask and prompt.strip():
        user_text = prompt.strip()
        st.session_state["rag_chat"].append({"role": "user", "content": user_text})
        with st.spinner("생성 중…"):
            res = query_rag(
                user_text,
                embed_model=embed_model,
                gen_model=gen_model,
                top_k=top_k,
                temperature=temperature,
            )
            answer = res["answer"]
            source_count = len(res.get("sources", []))
            mode = "hybrid" if res.get("contexts") else "gen_only"
            if st.session_state["rag_show_context"] and res.get("sources"):
                with st.expander("Context", expanded=False):
                    for s in res["sources"]:
                        st.markdown(f"**{s['source']} · chunk {s['chunk']}**")
                        st.code(s["snippet"], language="markdown")
        st.session_state["rag_chat"].append({"role": "assistant", "content": answer, "source_count": source_count, "mode": mode})
        st.rerun()


def render_processing_tab(use_ocr: bool, chunk_size: int, chunk_overlap: int):
    if st.session_state.get("is_processing", False):
        st.info("이미 처리 중입니다.")
        return

    try:
        files = scan_raw_files()
        st.subheader("Processing")
        if not files:
            st.warning("지원 형식 파일이 없습니다.")
            return

        selected = st.multiselect(
            "처리할 파일",
            [p.name for p in files],
            default=[p.name for p in files[:min(5, len(files))]],
        )

        c1, c2 = st.columns(2)
        with c1:
            start_parse = st.button("Parse 시작", use_container_width=True)
        with c2:
            clear_after = st.checkbox("처리 후 재실행", value=False)

        status_box = st.empty()
        progress_box = st.progress(0, text="대기 중")
        live_box = st.empty()
        results_box = st.empty()

        if start_parse:
            st.session_state["is_processing"] = True
            try:
                results = []
                total = max(1, len(selected))

                for idx, name in enumerate(selected, start=1):
                    path = RAW_DIR / name
                    if not path.exists():
                        status_box.warning(f"파일 없음: {name}")
                        continue

                    status_box.info(f"처리 중: {name}")
                    st.session_state["current_file"] = name
                    st.session_state["current_stage"] = "start"

                    converter = build_converter(use_ocr)
                    splitter = build_splitter(chunk_size, chunk_overlap)

                    file_info = {
                        "path": path,
                        "name": name,
                        "ext": path.suffix,
                        "use_ocr": use_ocr,
                    }

                    logs, success = process_one_file(
                        file_info=file_info,
                        converter=converter,
                        splitter=splitter,
                        output_dir=str(OUTPUT_DIR),
                        chunk_size=chunk_size,
                        chunk_overlap=chunk_overlap,
                    )

                    results.append({
                        "file": name,
                        "success": success,
                        "log_count": len(logs),
                    })

                    with st.expander(f"로그: {name}", expanded=not success):
                        for item in logs:
                            cls = item.get("cls", "log-info")
                            msg = item.get("msg", "")
                            if cls == "log-ok":
                                st.success(msg)
                            elif cls == "log-warn":
                                st.warning(msg)
                            else:
                                st.write(msg)

                    progress_box.progress(idx / total, text=f"{idx}/{total} 처리 완료")
                    live_box.write(
                        f"현재 파일: {st.session_state.get('current_file', '-') } | "
                        f"단계: {st.session_state.get('current_stage', '-')}"
                    )
                    time.sleep(0.05)

                if results:
                    st.success(f"{len(results)}개 처리 완료")
                    results_box.dataframe(pd.DataFrame(results), use_container_width=True, hide_index=True)

                if clear_after:
                    st.caption("처리 후 자동 재실행은 꺼져 있습니다. 필요하면 버튼을 다시 누르세요.")

            finally:
                st.session_state["is_processing"] = False

    except Exception as e:
        safe_log_exception(f"render_processing_tab failed: {e}")


def render_analysis_tab():
    if st.session_state.get("is_processing", False):
        st.info("청킹 처리 중입니다. 분석 탭은 잠시 후 다시 확인하세요.")
        return

    st.subheader("Analysis")
    md_files = sorted(OUTPUT_DIR.glob("*.md"), key=lambda p: p.name.lower())
    if not md_files:
        st.info("분석할 md 파일이 없습니다.")
        return

    choice = st.selectbox("md 파일 선택", [p.name for p in md_files])
    target = OUTPUT_DIR / choice
    text = target.read_text(encoding="utf-8", errors="ignore")
    chunk_path = OUTPUT_DIR / f"{target.stem}_chunks.txt"
    chunks_text = chunk_path.read_text(encoding="utf-8", errors="ignore") if chunk_path.exists() else ""
    key = f"analysis_text_{target.name}"

    if key not in st.session_state or st.session_state.get("analysis_loaded_file") != target.name:
        st.session_state[key] = text
        st.session_state["analysis_loaded_file"] = target.name

    noise = estimate_noise_score(text)
    c1, c2 = st.columns([1, 2])

    with c1:
        render_noise_bar(noise["score"], noise["usable"], noise["level"])
        st.metric("noise", f"{noise['score']:.1f}/100")
        st.metric("사용 가능", "YES" if noise["usable"] else "NO")
        st.metric("구간", noise["level"])
        st.caption(f"reason: {noise['reason']}")
        copy_clicked = st.button("복사", use_container_width=True)
        save_clicked = st.button("수정본 저장", use_container_width=True)

        if copy_clicked:
            st.code(st.session_state.get(key, ""), language="markdown")

        if save_clicked:
            target.write_text(st.session_state.get(key, text), encoding="utf-8")
            st.success("저장됨")
            st.rerun()

    with c2:
        tab_a, tab_b = st.tabs(["md 본문", "chunks"])
        with tab_a:
            st.text_area("내용", key=key, height=520)
        with tab_b:
            st.text_area("chunks", value=chunks_text, height=520, key=f"chunks_{target.name}")


def main():
    ensure_dirs()
    
    # Configure logging for Streamlit app
    logging.basicConfig(
        level=logging.INFO,
        format='%(asctime)s - %(name)s - %(levelname)s - %(message)s',
        handlers=[
            logging.FileHandler("logs/dbma_streamlit.log"),
            logging.StreamHandler()
        ]
    )
    logger = logging.getLogger(__name__)

    if "is_processing" not in st.session_state:
        st.session_state["is_processing"] = False
    if "embed_model" not in st.session_state:
        st.session_state["embed_model"] = DEFAULT_EMBED_MODEL
    if "gen_model" not in st.session_state:
        st.session_state["gen_model"] = DEFAULT_GEN_MODEL
    if "chunk_size" not in st.session_state:
        st.session_state["chunk_size"] = DEFAULT_CHUNK_SIZE
    if "chunk_overlap" not in st.session_state:
        st.session_state["chunk_overlap"] = DEFAULT_CHUNK_OVERLAP
    if "top_k" not in st.session_state:
        st.session_state["top_k"] = RAG_TOP_K
    if "temperature" not in st.session_state:
        st.session_state["temperature"] = DEFAULT_TEMPERATURE

    st.title(f"DBMAr {APP_VERSION}")
    st.caption("Document parsing / cleaning / chunking / monitoring / RAG / trendy chat")

    with st.sidebar:
        st.header("Settings")
        use_ocr = st.checkbox("Use OCR", value=False)
        dynamic_models = list_ollama_models()
        embed_choices = dynamic_models or EMBED_MODEL_OPTIONS
        gen_choices = dynamic_models or GEN_MODEL_OPTIONS

        if st.session_state["embed_model"] not in embed_choices:
            st.session_state["embed_model"] = embed_choices[0]
        if st.session_state["gen_model"] not in gen_choices:
            st.session_state["gen_model"] = gen_choices[0]

        st.session_state["embed_model"] = st.selectbox(
            "Embedding model",
            embed_choices,
            index=embed_choices.index(st.session_state["embed_model"]),
        )
        st.session_state["gen_model"] = st.selectbox(
            "LLM model",
            gen_choices,
            index=gen_choices.index(st.session_state["gen_model"]),
        )
        st.session_state["chunk_size"] = st.number_input(
            "Chunk Size",
            value=int(st.session_state["chunk_size"]),
            min_value=100,
            step=100,
        )
        st.session_state["chunk_overlap"] = st.number_input(
            "Chunk Overlap",
            value=int(st.session_state["chunk_overlap"]),
            min_value=0,
            step=10,
        )
        st.session_state["top_k"] = st.slider(
            "Top K",
            min_value=1,
            max_value=10,
            value=int(st.session_state["top_k"]),
        )
        st.session_state["temperature"] = st.slider(
            "Temperature",
            min_value=0.0,
            max_value=1.5,
            value=float(st.session_state["temperature"]),
            step=0.05,
        )
        st.caption(f"Collection: {COLLECTION_NAME}")
        if st.button("Cache Clear"):
            cleanup_cache()
            st.success("Cache cleared")

    tab1, tab2, tab3 = st.tabs(["Parse", "Analyze", "RAG"])
    with tab1:
        render_processing_tab(
            use_ocr=use_ocr,
            chunk_size=int(st.session_state["chunk_size"]),
            chunk_overlap=int(st.session_state["chunk_overlap"]),
        )
    with tab2:
        render_analysis_tab()
    with tab3:
        render_trendy_chat_tab(
            embed_model=st.session_state["embed_model"],
            gen_model=st.session_state["gen_model"],
            chunk_size=int(st.session_state["chunk_size"]),
            chunk_overlap=int(st.session_state["chunk_overlap"]),
            top_k=int(st.session_state["top_k"]),
            temperature=float(st.session_state["temperature"]),
        )

if __name__ == "__main__":
    main()