#!/usr/bin/env python3
"""gate2_orchestrator.py - Gate 2 automation orchestrator.

Runs Phase A scripts in order, generates manifest.json + SUMMARY.md.
Phase B scripts (40/80/90) are NOT called by default - requires --include-mutating flag.

Task Order: C1-TASK-ORDER-GATE2-ORCHESTRATOR-SCAFFOLDING.md s3 Phase A
"""

import argparse
import hashlib
import json
import subprocess
import sys
from datetime import datetime, timezone
from pathlib import Path

# gate2_orchestrator.py lives at scripts/gate2/ — go up 3 levels for project root
PROJECT_ROOT = Path(__file__).resolve().parent.parent.parent
SCRIPTS_DIR = Path(__file__).resolve().parent
EVIDENCE_BASE = PROJECT_ROOT / "evidence" / "gate2"

PHASE_A_SCRIPTS = [
    "00_baseline.sh",
    "10_packaging_audit.py",
    "30_package_integrity.py",
    "50_runtime_smoke.py",
    "60_ui_pages.py",
    "61_citation_ui.py",
    "70_production_isolation.py",
    "95_evidence_verify.py",
]

PHASE_B_SCRIPTS = [
    "40_clean_install.sh",
    "80_reinstall_upgrade.sh",
    "90_uninstall.sh",
]


def run_script(script_path, cwd):
    result = {
        "script": script_path.name,
        "status": "UNKNOWN",
        "returncode": None,
        "stdout": "",
        "stderr": "",
    }
    try:
        if script_path.suffix == ".sh":
            proc = subprocess.run(
                ["bash", str(script_path)],
                cwd=str(cwd),
                capture_output=True,
                text=True,
                timeout=300,
            )
        elif script_path.suffix == ".py":
            venv_bin = Path.home() / "envs" / "dbma311" / "bin"
            proc = subprocess.run(
                [str(venv_bin / "python"), str(script_path)],
                cwd=str(cwd),
                capture_output=True,
                text=True,
                timeout=300,
            )
        else:
            result["status"] = "SKIP"
            result["reason"] = f"Unsupported extension: {script_path.suffix}"
            return result

        result["returncode"] = proc.returncode
        result["stdout"] = proc.stdout
        result["stderr"] = proc.stderr
        combined = (proc.stdout + proc.stderr).encode("utf-8")
        result["stdout_sha256"] = hashlib.sha256(combined).hexdigest()

        if proc.returncode == 0:
            result["status"] = "PASS"
        elif proc.returncode == 1:
            result["status"] = "FAIL"
        else:
            result["status"] = "ERROR"

    except subprocess.TimeoutExpired:
        result["status"] = "TIMEOUT"
    except Exception as exc:
        result["status"] = "ERROR"
        result["reason"] = str(exc)

    return result


def determine_gate_status(results):
    statuses = [r["status"] for r in results]
    if all(s == "PASS" for s in statuses):
        return "GREEN"
    elif any(s in ("FAIL", "ERROR", "TIMEOUT") for s in statuses):
        return "RED"
    else:
        return "HOLD"


def generate_summary(manifest, run_id):
    lines = [
        "# Gate 2 Orchestrator Summary",
        "",
        f"**Run ID**: `{run_id}`",
        f"**Timestamp**: {manifest.get('timestamp', 'N/A')}",
        f"**Status**: {manifest.get('overall_status', 'UNKNOWN')}",
        "",
        "## Phase A Results",
        "",
    ]
    for step in manifest.get("steps", []):
        icon = {"PASS": "\u2705", "FAIL": "\u274c", "ERROR": "\u26d4",
                "TIMEOUT": "\u23f1\u20e5", "SKIP": "\u23ed\u20e5"}.get(
            step["status"], "\u2753")
        lines.append(f"- {icon} `{step['script']}` - {step['status']}")

    lines.extend([
        "",
        "## Evidence Files",
        "",
    ])
    evidence_dir = EVIDENCE_BASE / run_id
    if evidence_dir.exists():
        for ev_file in sorted(evidence_dir.glob("*.json")):
            lines.append(f"- `{ev_file.name}`")

    lines.extend([
        "",
        "---",
        "*Generated by gate2_orchestrator.py*",
    ])
    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Gate 2 Orchestrator")
    parser.add_argument("--phase", choices=["A", "B", "all"], default="A")
    parser.add_argument("--include-mutating", action="store_true",
                        help="Include Phase B (mutating) scripts")
    parser.add_argument("--run-id", default=None, help="Custom run ID")
    args = parser.parse_args()

    if args.phase == "A" or args.phase == "all":
        scripts_to_run = list(PHASE_A_SCRIPTS)
    elif args.phase == "B":
        if not args.include_mutating:
            print("ERROR: Phase B requires --include-mutating flag")
            sys.exit(1)
        scripts_to_run = list(PHASE_B_SCRIPTS)
    else:
        scripts_to_run = []

    if not scripts_to_run:
        print(f"ERROR: No scripts to run for phase={args.phase}")
        sys.exit(1)

    run_id = args.run_id or datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%S")
    run_dir = EVIDENCE_BASE / run_id
    run_dir.mkdir(parents=True, exist_ok=True)

    print(f"=== Gate 2 Orchestrator ===")
    print(f"Run ID: {run_id}")
    print(f"Phase: {args.phase}")
    print(f"Scripts: {len(scripts_to_run)}")
    print()

    results = []
    for script_name in scripts_to_run:
        script_path = SCRIPTS_DIR / script_name
        if not script_path.exists():
            results.append({"script": script_name, "status": "SKIP",
                            "reason": f"Script not found: {script_path}"})
            print(f"\u23ed\u20e5  SKIP {script_name} (not found)")
            continue

        print(f"\u25b6\ufe0f  Running {script_name}...")
        result = run_script(script_path, PROJECT_ROOT)
        results.append(result)

        icon = {"PASS": "\u2705", "FAIL": "\u274c", "ERROR": "\u26d4",
                "TIMEOUT": "\u23f1\u20e5", "SKIP": "\u23ed\u20e5"}.get(
            result["status"], "\u2753")
        print(f"  {icon} {script_name} - {result['status']}")

    overall_status = determine_gate_status(results)

    manifest = {
        "run_id": run_id,
        "timestamp": datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ"),
        "phase": args.phase,
        "overall_status": overall_status,
        "total_scripts": len(scripts_to_run),
        "passed": sum(1 for r in results if r["status"] == "PASS"),
        "failed": sum(1 for r in results if r["status"] in ("FAIL", "ERROR", "TIMEOUT")),
        "skipped": sum(1 for r in results if r["status"] == "SKIP"),
        "steps": results,
    }

    manifest_file = run_dir / "manifest.json"
    manifest_file.write_text(json.dumps(manifest, indent=2, ensure_ascii=False), encoding="utf-8")

    summary_md = generate_summary(manifest, run_id)
    summary_file = run_dir / "SUMMARY.md"
    summary_file.write_text(summary_md, encoding="utf-8")

    print()
    print(f"=== Overall: GATE2_STATUS={overall_status} ===")
    print(f"Passed: {manifest['passed']}/{manifest['total_scripts']}")
    print(f"Evidence: {run_dir}")
    print(f"Manifest: {manifest_file}")
    print(f"Summary:  {summary_file}")
    print(f"GATE2_STATUS={overall_status}")

    sys.exit(0 if overall_status in ("GREEN", "HOLD") else 1)


if __name__ == "__main__":
    main()
